FROM ubuntu:16.04
 
RUN apt-get update && \
RUN apt-get install -y python && \
RUN apt-get update && \
RUN apt-add-repository -y ppa:ansible/ansible && \
RUN apt-get update && \
RUN apt-get install -y ansible

RUN mkdir /ansible
WORKDIR /ansible

CMD [ "ansible", "--version" ]
