FROM ubuntu
 
RUN \
  apt-get update && \
  apt-get install -y python && \
  apt-get update && \
  apt-add-repository -y ppa:ansible/ansible && \
  apt-get update && \
  apt-get install -y ansible && \

RUN mkdir /ansible
WORKDIR /ansible

CMD [ "ansible", "--version" ]
